// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SolarVolt.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260701233715_AddDeletedStatusToUnitEnum")]
    partial class AddDeletedStatusToUnitEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolarVolt.Models.Appliance", b =>
                {
                    b.Property<int>("ApplianceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplianceID"));

                    b.Property<int>("DefalutWattage")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplianceID");

                    b.ToTable("Appliances");
                });

            modelBuilder.Entity("SolarVolt.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SolarVolt.Models.Energy_Input_Item", b =>
                {
                    b.Property<int>("Energy_Input_ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Energy_Input_ItemID"));

                    b.Property<int>("ApplianceID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SessionID")
                        .HasColumnType("int");

                    b.Property<int>("WattOverride")
                        .HasColumnType("int");

                    b.HasKey("Energy_Input_ItemID");

                    b.HasIndex("ApplianceID");

                    b.HasIndex("SessionID");

                    b.ToTable("Energy_Input_Items");
                });

            modelBuilder.Entity("SolarVolt.Models.Energy_Input_Session", b =>
                {
                    b.Property<int>("Energy_Input_SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Energy_Input_SessionID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalWatt")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Energy_Input_SessionID");

                    b.HasIndex("UserID");

                    b.ToTable("Energy_Input_Sessions");
                });

            modelBuilder.Entity("SolarVolt.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SolarVolt.Models.Order_Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("Order_Items");
                });

            modelBuilder.Entity("SolarVolt.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int>("WattCapacity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SolarVolt.Models.Product_Unit", b =>
                {
                    b.Property<int>("Product_UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Product_UnitId"));

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Product_UnitId");

                    b.HasIndex("ProductID");

                    b.ToTable("Product_Units");
                });

            modelBuilder.Entity("SolarVolt.Models.Recommendation", b =>
                {
                    b.Property<int>("RecommendationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecommendationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SessionID")
                        .HasColumnType("int");

                    b.Property<int>("TotalWattage")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("RecommendationID");

                    b.HasIndex("SessionID")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("SolarVolt.Models.Recommendation_Item", b =>
                {
                    b.Property<int>("Recommendation_ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Recommendation_ItemID"));

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RecommendationID")
                        .HasColumnType("int");

                    b.HasKey("Recommendation_ItemID");

                    b.HasIndex("ProductID");

                    b.HasIndex("RecommendationID");

                    b.ToTable("Recommendation_Items");
                });

            modelBuilder.Entity("SolarVolt.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SolarVolt.Models.Energy_Input_Item", b =>
                {
                    b.HasOne("SolarVolt.Models.Appliance", "appliance")
                        .WithMany("Energy_Input_Items_List")
                        .HasForeignKey("ApplianceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolarVolt.Models.Energy_Input_Session", "energy_Input_Session")
                        .WithMany("energy_Input_Items_List")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("appliance");

                    b.Navigation("energy_Input_Session");
                });

            modelBuilder.Entity("SolarVolt.Models.Energy_Input_Session", b =>
                {
                    b.HasOne("SolarVolt.Models.User", "user")
                        .WithMany("Energy_Input_Sessions_List")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("SolarVolt.Models.Order", b =>
                {
                    b.HasOne("SolarVolt.Models.User", "user")
                        .WithMany("Orders_List")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("SolarVolt.Models.Order_Item", b =>
                {
                    b.HasOne("SolarVolt.Models.Order", "order")
                        .WithMany("Order_Items_List")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolarVolt.Models.Product", "product")
                        .WithMany("Order_Items_List")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");

                    b.Navigation("product");
                });

            modelBuilder.Entity("SolarVolt.Models.Product", b =>
                {
                    b.HasOne("SolarVolt.Models.Category", "Category")
                        .WithMany("products_List")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SolarVolt.Models.Product_Unit", b =>
                {
                    b.HasOne("SolarVolt.Models.Product", "product")
                        .WithMany("Product_Units_List")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("SolarVolt.Models.Recommendation", b =>
                {
                    b.HasOne("SolarVolt.Models.Energy_Input_Session", "energy_Input_Session")
                        .WithOne("recommendation")
                        .HasForeignKey("SolarVolt.Models.Recommendation", "SessionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolarVolt.Models.User", "user")
                        .WithMany("Recommendations_List")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("energy_Input_Session");

                    b.Navigation("user");
                });

            modelBuilder.Entity("SolarVolt.Models.Recommendation_Item", b =>
                {
                    b.HasOne("SolarVolt.Models.Product", "product")
                        .WithMany("Recommendation_Items_List")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolarVolt.Models.Recommendation", "recommendation")
                        .WithMany("Recommendation_Items_List")
                        .HasForeignKey("RecommendationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("recommendation");
                });

            modelBuilder.Entity("SolarVolt.Models.Appliance", b =>
                {
                    b.Navigation("Energy_Input_Items_List");
                });

            modelBuilder.Entity("SolarVolt.Models.Category", b =>
                {
                    b.Navigation("products_List");
                });

            modelBuilder.Entity("SolarVolt.Models.Energy_Input_Session", b =>
                {
                    b.Navigation("energy_Input_Items_List");

                    b.Navigation("recommendation");
                });

            modelBuilder.Entity("SolarVolt.Models.Order", b =>
                {
                    b.Navigation("Order_Items_List");
                });

            modelBuilder.Entity("SolarVolt.Models.Product", b =>
                {
                    b.Navigation("Order_Items_List");

                    b.Navigation("Product_Units_List");

                    b.Navigation("Recommendation_Items_List");
                });

            modelBuilder.Entity("SolarVolt.Models.Recommendation", b =>
                {
                    b.Navigation("Recommendation_Items_List");
                });

            modelBuilder.Entity("SolarVolt.Models.User", b =>
                {
                    b.Navigation("Energy_Input_Sessions_List");

                    b.Navigation("Orders_List");

                    b.Navigation("Recommendations_List");
                });
#pragma warning restore 612, 618
        }
    }
}
